# Generated by Django 4.2.2 on 2023-08-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_related_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('week', models.DateField()),
                ('monday_1', models.CharField(max_length=20)),
                ('monday_2', models.CharField(max_length=20)),
                ('tuesday_1', models.CharField(max_length=20)),
                ('tuesday_2', models.CharField(max_length=20)),
                ('wednesday_1', models.CharField(max_length=20)),
                ('wednesday_2', models.CharField(max_length=20)),
                ('thursday_1', models.CharField(max_length=20)),
                ('thursday_2', models.CharField(max_length=20)),
                ('friday_1', models.CharField(max_length=20)),
                ('friday_2', models.CharField(max_length=20)),
                ('saturday_1', models.CharField(max_length=20)),
                ('saturday_2', models.CharField(max_length=20)),
                ('sunday_1', models.CharField(max_length=20)),
                ('sunday_2', models.CharField(max_length=20)),
            ],
        ),
    ]
