# Generated by Django 4.2.2 on 2023-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_rename_hour_00_01_cafeworkinghours_hour_0_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_00_01',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_01_02',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_02_03',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_03_04',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_04_05',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_05_06',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_06_07',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_07_08',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_08_09',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_09_10',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_10_11',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_11_12',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_12_13',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_13_14',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_14_15',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_15_16',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_16_17',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_17_18',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_18_19',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_19_20',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_20_21',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_21_22',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_22_23',
        ),
        migrations.RemoveField(
            model_name='scheduleforoneday',
            name='hour_23_24',
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_00_01',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_01_02',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_02_03',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_03_04',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_04_05',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_05_06',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_06_07',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_07_08',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_08_09',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_09_10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_10_11',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_11_12',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_12_13',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_13_14',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_14_15',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_15_16',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_16_17',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_17_18',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_18_19',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_19_20',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_20_21',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_21_22',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_22_23',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='scheduleforoneday',
            name='hour_23_24',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
