# Generated by Django 4.2.2 on 2023-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_rename_hour_00_01_scheduleforoneday_hour_0_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleforoneday',
            name='cafe',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
